version: '3' 
services:
  photran-eclipse-docker:
    image: photran-eclipse-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photran-eclipse
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - DISPLAY=${DISPLAY:-":0.0"}
    env_file:
      - ./.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./eclipse-workspace:/home/developer/eclipse-workspace
      - ./.eclipse:/home/developer/.eclipse

